import React from 'react'
import Head from 'next/head'
import type { NextPage } from 'next'
import ThreejsCanvas from '../components/ThreejsCanvas/ThreejsCanvas'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ThreejsCanvas />
      </main>
    </div>
  )
}

export default Home
